server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /api/ {
        resolver 127.0.0.11 valid=10s;
        set $backend "user-center:8081";
        proxy_pass http://$backend;
    }
}
