spring:
  datasource:
    url: jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

flowable:
  database-schema-update: true
  async-executor-activate: true

logging:
  level:
    org.flowable: INFO
    com.flowable: DEBUG
